import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader, SUPPORT_EMAIL } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Security Model", description: "What CodexTheme changes, what it never touches, and how to restore Codex safely.", alternates: { canonical: "/security" } };

export default function SecurityPage() { return <div className="site-shell"><SiteHeader /><main className="subpage section-wrap"><article className="article-page"><Link className="back-link" href="/">← Back to the home page</Link><p className="eyebrow"><span /> SECURITY MODEL</p><h1>Security model</h1><p className="article-lead">Before copying a command, you should know exactly what it changes and what it never touches.</p>
  <section className="article-block"><h2>Codex.app stays untouched</h2><p>The runtime binds Chromium DevTools Protocol to 127.0.0.1 and injects CSS into the current Codex renderer. It does not rewrite Codex.app, app.asar, or the official code signature, and it never requires sudo or administrator access.</p></section>
  <section className="article-block"><h2>Themes are data, not programs</h2><p>Installable theme packages contain JSON declarations, CSS, and embedded raster images. The runtime rejects remote CSS resources, and themes cannot carry or execute JavaScript. Every downloaded private package is size-limited, hashed, validated, and safety-linted before Codex is touched.</p></section>
  <section className="article-block"><h2>Private uploads expire</h2><p>Your browser prepares the preview locally. Nothing uploads until you select Create private skin. The original filename and image metadata are not sent; the server re-encodes the processed image into a private package. Its unlisted link expires after 24 hours, and the stored file is deleted during the next daily cleanup window. Pasting the guided install into a Code Agent sends the temporary ID to that Agent provider; use the Terminal fallback if you do not want the ID in an Agent conversation.</p></section>
  <section className="article-block"><h2>Reapply stays local</h2><p>After the first successful private apply, the validated package is cached with owner-only permissions on your Mac. Reapply reads that local copy, so it keeps working after the temporary cloud link expires.</p></section>
  <section className="article-block"><h2>Codex never restarts silently</h2><p>If Codex is running and must be reopened, the CLI warns that unsent input may be lost. The guided Agent copy requests an interactive PTY so this decision stays with you; non-interactive environments cancel by default. After approval, an owner-only one-shot helper completes the restart and exits. It stores only a public theme slug or local cache hash and is not a persistent background service.</p></section>
  <section className="article-block"><h2>Pinned releases and public source</h2><p>Every site command is pinned to @codextheme/cli@0.2.5. The source is public, and the repository preserves its Apache-2.0 upstream license, Git history, NOTICE, and exact provenance.</p></section>
  <section className="article-block"><h2>Restore the official appearance</h2><p>Run restore from the same pinned release:</p><code className="inline-code">npx --yes @codextheme/cli@0.2.5 restore</code><p>Restore handles both the active renderer and Codex appearance settings. If recovery is only partial, the active state remains and the CLI returns an explicit error.</p></section>
  <section className="article-block"><h2>Get help</h2><p>For installation or compatibility help, contact <a className="article-link" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Never send conversations, tokens, personal paths, or other private information.</p></section>
  <section className="article-block"><h2>Independent project</h2><p>CodexTheme is an independent open-source project. It is not affiliated with, sponsored by, or endorsed by OpenAI. Codex is a product and trademark of its respective owner.</p></section>
  </article></main><SiteFooter /></div>; }
