import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader, SUPPORT_EMAIL } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Security Model", description: "What CodexTheme changes, what it never touches, and how to restore Codex safely.", alternates: { canonical: "/security" } };

export default function SecurityPage() { return <div className="site-shell"><SiteHeader /><main className="subpage section-wrap"><article className="article-page"><Link className="back-link" href="/">← Back to the home page</Link><p className="eyebrow"><span /> SECURITY MODEL</p><h1>Security model</h1><p className="article-lead">Before copying a command, you should know exactly what it changes and what it never touches.</p>
  <section className="article-block"><h2>Codex.app stays untouched</h2><p>The runtime binds Chromium DevTools Protocol to 127.0.0.1 and injects CSS into the current Codex renderer. It does not rewrite Codex.app, app.asar, or the official code signature, and it never requires sudo or administrator access.</p></section>
  <section className="article-block"><h2>Themes are data, not programs</h2><p>Installable theme packages contain JSON declarations, CSS, and embedded JPEG images. The runtime rejects remote CSS resources, and themes cannot carry or execute JavaScript. Published theme bytes are bundled directly into the pinned CLI, so reapply never contacts this website.</p></section>
  <section className="article-block"><h2>Codex never restarts silently</h2><p>If Codex is running and must be reopened, the CLI warns that unsent input may be lost. It continues only after an explicit y in an interactive terminal; non-interactive environments cancel by default.</p></section>
  <section className="article-block"><h2>Pinned releases and public source</h2><p>Every site command is pinned to @codextheme/cli@0.1.1. The source is public, and the runtime preserves the Apache-2.0 license, Git history, NOTICE, and exact provenance for CodeDrobe Core 0.3.0.</p></section>
  <section className="article-block"><h2>Restore the official appearance</h2><p>Run restore from the same pinned release:</p><code className="inline-code">npx --yes @codextheme/cli@0.1.1 restore</code><p>Restore handles both the active renderer and Codex appearance settings. If recovery is only partial, the active state remains and the CLI returns an explicit error.</p></section>
  <section className="article-block"><h2>Get help</h2><p>For installation or compatibility help, contact <a className="article-link" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Never send conversations, tokens, personal paths, or other private information.</p></section>
  <section className="article-block"><h2>Independent project</h2><p>CodexTheme is an independent open-source project. It is not affiliated with, sponsored by, or endorsed by OpenAI. Codex is a product and trademark of its respective owner.</p></section>
  </article></main><SiteFooter /></div>; }
