import assert from "node:assert/strict";
import test from "node:test";
import { buildPrivateSkinPackage } from "../../../apps/site/app/lib/private-skin-package.mjs";
import { createRuntime } from "../src/runtime.mjs";

function coreHarness({ running = false, restore } = {}) {
  const calls = [];
  const core = {
    getAdapter(id) { calls.push(["getAdapter", id]); return { id: "codex", defaultPort: 9222 }; },
    async discoverApp() { calls.push(["discoverApp"]); return { executable: "/Applications/Codex" }; },
    async findTargets() { calls.push(["findTargets"]); return []; },
    async findRunningPids() { calls.push(["findRunningPids"]); return running ? [123] : []; },
    async restoreSkin() {
      calls.push(["restoreSkin"]);
      return restore ?? {
        renderer: { restored: false, code: "CODEXTHEME_TARGET_TIMEOUT" },
        host: { restored: false, reason: "missing-backup" },
      };
    },
    async launchApp() { calls.push(["launchApp"]); return { targets: 1, pid: 456 }; },
    async applySkin() { throw new Error("not used"); },
    async readThemePackage() { throw new Error("not used"); },
    resolveThemeTarget() { throw new Error("not used"); },
    validateThemePackage() {},
    lintThemePackage() { return []; },
  };
  return { calls, runtime: createRuntime({ core, platform: "darwin" }) };
}

test("runtime recovery restores host state and relaunches Codex when it is absent", async () => {
  const app = coreHarness();
  const result = await app.runtime.recover();

  assert.equal(result.recovered, true);
  assert.deepEqual(app.calls.filter(([name]) => ["restoreSkin", "launchApp"].includes(name)), [
    ["restoreSkin"],
    ["launchApp"],
  ]);
});

test("runtime recovery does not launch a second Codex process when one is still running", async () => {
  const app = coreHarness({ running: true });
  const result = await app.runtime.recover();

  assert.equal(result.recovered, true);
  assert.equal(app.calls.some(([name]) => name === "launchApp"), false);
});

test("runtime recovery reports a partial restore without claiming success", async () => {
  const app = coreHarness({
    running: true,
    restore: {
      renderer: { restored: true },
      host: { restored: false, reason: "permission-denied" },
    },
  });
  const result = await app.runtime.recover();

  assert.equal(result.recovered, false);
});

test("runtime accepts the exact private package generated by the website", async () => {
  const bundle = JSON.parse(buildPrivateSkinPackage({
    id: "n0z6o000.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    exportedAt: "2026-07-26T00:00:00.000Z",
    image: Buffer.from("safe-image"),
    settings: {},
  }));
  const runtime = createRuntime({ platform: "darwin" });

  const resolved = await runtime.loadThemeBundle(bundle);

  assert.equal(resolved.theme.displayName, "Private Custom Skin");
  assert.match(resolved.css, /html\.codextheme-codex-skin/);
});

test("runtime accepts website packages whose private token starts with base64url punctuation", async () => {
  const token = "-13i3j9pfz1hzu8hrjdn".padEnd(32, "a");
  const bundle = JSON.parse(buildPrivateSkinPackage({
    id: `n0z6o000.${token}`,
    exportedAt: "2026-07-26T00:00:00.000Z",
    image: Buffer.from("safe-image"),
    settings: {},
  }));
  const runtime = createRuntime({ platform: "darwin" });

  assert.match(bundle.theme.id, /^private-[a-z0-9]{20}$/u);
  await assert.doesNotReject(() => runtime.loadThemeBundle(bundle));
});

test("runtime keeps lint diagnostics fatal for non-private themes", async () => {
  const bundle = {
    theme: { id: "catalog-theme", displayName: "Catalog Theme" },
    targets: { codex: { css: "body { color: red; }" } },
  };
  const core = {
    getAdapter() { return { id: "codex" }; },
    validateThemePackage(value) { return value; },
    lintThemePackage() { return [{ code: "unsafe-maintenance-pattern" }]; },
    resolveThemeTarget() { throw new Error("must not resolve a lint-failing catalog theme"); },
  };
  const runtime = createRuntime({ core, platform: "darwin" });

  await assert.rejects(
    runtime.loadThemeBundle(bundle),
    (error) => error?.code === "E_DOM_INCOMPATIBLE",
  );
});

test("runtime anchors legacy cached private artwork without mutating the cache bundle", async () => {
  const legacyCss = `html.codedrobe-codex-skin body::before {
  content: "";
  position: fixed;
  inset: -5%;
  background-image: linear-gradient(rgba(5, 6, 10, 0.42), rgba(5, 6, 10, 0.42)), var(--codedrobe-image-session-bg);
  background-position: 40% 65%;
  background-size: cover;
}

html.codedrobe-codex-skin .dream-home {
  position: relative;
  isolation: isolate;
  background-image: linear-gradient(rgba(5, 6, 10, 0.42), rgba(5, 6, 10, 0.42)), var(--codedrobe-image-hero) !important;
  background-position: 40% 65% !important;
  background-size: cover !important;
}`;
  const bundle = {
    theme: { id: "private-aaaaaaaaaaaaaaaaaaaa", displayName: "Private Custom Skin" },
    targets: { codex: { css: legacyCss } },
  };
  const core = {
    getAdapter() { return { id: "codex" }; },
    validateThemePackage(value) {
      return {
        ...value,
        format: "codextheme-theme",
        targets: {
          ...value.targets,
          codex: {
            ...value.targets.codex,
            css: value.targets.codex.css
              .replaceAll("codedrobe-codex-skin", "codextheme-codex-skin")
              .replaceAll("--codedrobe-image-", "--codextheme-image-"),
          },
        },
      };
    },
    lintThemePackage() { return []; },
    resolveThemeTarget(value) { return value.targets.codex; },
  };
  const runtime = createRuntime({ core, platform: "darwin" });

  const resolved = await runtime.loadThemeBundle(bundle);

  assert.match(resolved.css, /body:has\(\.dream-home\)::before\s*\{[^}]*var\(--codextheme-image-hero\)/s);
  const homeSurface = resolved.css.match(/\.dream-home\s*\{([^}]*)\}/s);
  assert.ok(homeSurface);
  assert.doesNotMatch(homeSurface[1], /var\(--codextheme-image-hero\)/);
  assert.doesNotMatch(resolved.css, /codedrobe/iu);
  assert.equal(bundle.targets.codex.css, legacyCss);
});
